name: Deploy AkiliPesa

on:
  push:
    branches: [ main ]
    # Re-run only when these change (adjust as needed)
    paths:
      - 'firebase/functions/**'
      - 'firebase/firestore.rules'
      - 'firebase.json'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # <-- required for OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Auth to Google Cloud using Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      # (Optional) Install gcloud – handy for debugging
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # Install and build Cloud Functions
      - name: Install functions deps
        run: npm ci
        working-directory: firebase/functions

      - name: Build functions
        run: npm run build
        working-directory: firebase/functions

      # Deploy from repo root so firebase.json is picked up
      - name: Deploy to Firebase (functions + rules)
        run: npx firebase-tools deploy --project akilipesa-prod --only functions,firestore:rules --non-interactive
