name: Deploy AkiliPesa
on:
  push:
    branches: [ main ]
    paths:
      - 'firebase/functions/**'
      - 'firebase/firestore.rules'
      - 'firebase.json'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      # (Optional) build functions if using TypeScript
      - run: npm ci
        working-directory: firebase/functions
      - run: npm run build
        working-directory: firebase/functions

      # Seed/update Cloud Functions secrets (idempotent)
      - name: Seed CF secrets
        run: |
          npx firebase-tools functions:secrets:set AGORA_APP_ID --data "${{ secrets.AGORA_APP_ID }}" --project akilipesa-prod --force
          npx firebase-tools functions:secrets:set AGORA_APP_CERT --data "${{ secrets.AGORA_APP_CERT }}" --project akilipesa-prod --force
          npx firebase-tools functions:secrets:set RTC_PROVIDER --data "${{ vars.RTC_PROVIDER }}" --project akilipesa-prod --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # Deploy functions + rules (add hosting/storage if you want)
      - name: Deploy to Firebase
        run: npx firebase-tools deploy --only functions,firestore:rules --project akilipesa-prod --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
