name: Deploy Functions (WIF)

on:
  push:
    branches: [ main ]
    paths:
      - 'firebase/functions/**'
      - 'firebase/firestore.rules'
      - 'firebase.json'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Authenticate to Google Cloud (WIF)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          export_environment_variables: true

      # (recommended; some tools look for gcloud on PATH)
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Firebase CLI
        run: |
          npm i -g firebase-tools@latest
          firebase --version

      - name: Install & build Cloud Functions
        working-directory: firebase/functions
        run: |
          npm ci
          npm run build

      - name: Sanity check auth
        run: |
          gcloud auth list
          firebase --version
          firebase projects:list --non-interactive || true

      # ---------- FIXED SECRETS SEEDING ----------
      - name: Seed Firebase Secrets (idempotent)
        env:
          PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          AGORA_APP_ID: ${{ secrets.AGORA_APP_ID }}
          AGORA_APP_CERT: ${{ secrets.AGORA_APP_CERT }}
          RTC_PROVIDER: ${{ vars.RTC_PROVIDER }}
        run: |
          echo -n "$AGORA_APP_ID"   | firebase functions:secrets:set AGORA_APP_ID   --project "$PROJECT_ID" --force --non-interactive
          echo -n "$AGORA_APP_CERT" | firebase functions:secrets:set AGORA_APP_CERT --project "$PROJECT_ID" --force --non-interactive
          echo -n "$RTC_PROVIDER"   | firebase functions:secrets:set RTC_PROVIDER   --project "$PROJECT_ID" --force --non-interactive
      # -------------------------------------------

      - name: Deploy Functions + Firestore rules
        run: |
          firebase deploy \
            --only functions,firestore:rules \
            --project ${{ vars.FIREBASE_PROJECT_ID }} \
            --non-interactive
