name: Deploy Functions (WIF)

on:
  push:
    branches: [ main ]
    paths:
      - 'firebase/functions/**'
      - 'firebase/firestore.rules'
      - 'firebase.json'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 🔐 WIF: export env vars so firebase-tools picks up ADC
      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }} # projects/26736767264/locations/global/workloadIdentityPools/github/providers/github-oidc
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}                # firebase-deployer@akilipesa-prod.iam.gserviceaccount.com
          export_environment_variables: true

      - name: Install gcloud (optional, but keeps SDK aligned)
        uses: google-github-actions/setup-gcloud@v2

      - name: Install functions deps
        working-directory: firebase/functions
        run: npm ci

      - name: Build functions
        working-directory: firebase/functions
        run: npm run build

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@latest

      # ✅ New syntax for seeding secrets (no --data flag)
      - name: Seed Agora secrets (idempotent)
        env:
          AGORA_APP_ID: ${{ secrets.AGORA_APP_ID }}
          AGORA_APP_CERT: ${{ secrets.AGORA_APP_CERT }}
          RTC_PROVIDER: ${{ vars.RTC_PROVIDER }}
        run: |
          printf "%s" "$AGORA_APP_ID"   | firebase functions:secrets:set AGORA_APP_ID   --project akilipesa-prod --force
          printf "%s" "$AGORA_APP_CERT" | firebase functions:secrets:set AGORA_APP_CERT --project akilipesa-prod --force
          printf "%s" "$RTC_PROVIDER"   | firebase functions:secrets:set RTC_PROVIDER   --project akilipesa-prod --force

      # Deploy Functions + Firestore rules
      - name: Deploy Functions + Firestore rules
        run: firebase deploy --only functions,firestore:rules --project akilipesa-prod --non-interactive
