name: Deploy Functions (WIF)

on:
  push:
    branches: [ main ]
    paths:
      - 'firebase/functions/**'
      - 'firebase/firestore.rules'
      - 'firebase.json'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & build Cloud Functions
        working-directory: firebase/functions
        run: |
          npm ci
          npm run build

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Seed Firebase Secrets (idempotent)
        run: |
          firebase functions:secrets:set AGORA_APP_ID    --project akilipesa-prod --data "${{ secrets.AGORA_APP_ID }}" --force
          firebase functions:secrets:set AGORA_APP_CERT  --project akilipesa-prod --data "${{ secrets.AGORA_APP_CERT }}" --force
          firebase functions:secrets:set RTC_PROVIDER    --project akilipesa-prod --data "${{ vars.RTC_PROVIDER }}" --force

      - name: Deploy Functions + Rules
        run: firebase deploy --only functions,firestore:rules --project akilipesa-prod --non-interactive
