name: Deploy AkiliPesa

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # WIF: create short-lived SA creds + export ADC env vars
      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          export_environment_variables: true

      # (recommended; some tools look for gcloud on PATH)
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@latest

      - name: Install deps (functions)
        working-directory: firebase/functions
        run: npm ci

      - name: Build functions
        working-directory: firebase/functions
        run: npm run build

      - name: Sanity check auth
        run: |
          gcloud auth list
          firebase --version
          firebase projects:list --non-interactive || true

      # Seed Cloud Functions secrets (idempotent, non-interactive)
      - name: Seed CF secrets
        env:
          PROJECT_ID: akilipesa-prod
          AGORA_APP_ID: ${{ secrets.AGORA_APP_ID }}
          AGORA_APP_CERT: ${{ secrets.AGORA_APP_CERT }}
          RTC_PROVIDER: ${{ vars.RTC_PROVIDER }}
        run: |
          set -euo pipefail
          firebase --version

          printf '%s' "$AGORA_APP_ID"  | firebase functions:secrets:set AGORA_APP_ID  --project "$PROJECT_ID" --force
          printf '%s' "$AGORA_APP_CERT"| firebase functions:secrets:set AGORA_APP_CERT --project "$PROJECT_ID" --force
          printf '%s' "$RTC_PROVIDER"  | firebase functions:secrets:set RTC_PROVIDER  --project "$PROJECT_ID" --force

      - name: Deploy Functions + Firestore rules
        run: firebase deploy --only functions,firestore:rules --project akilipesa-prod --non-interactive
