name: Deploy Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'firebase/functions/**'
      - 'firebase/firestore.rules'
      - 'firebase.json'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            firebase/functions/package-lock.json

      - name: Install workspace deps
        run: npm ci --workspaces

      - name: Build Cloud Functions (TypeScript)
        run: npm run build
        working-directory: firebase/functions

      - name: Deploy Functions + Firestore rules
        run: npx firebase-tools deploy --only functions,firestore:rules --project "${{ vars.FIREBASE_PROJECT_ID }}" --non-interactive --token "${{ secrets.FIREBASE_TOKEN }}"
