name: Deploy Firebase Functions

on:
  push:
    branches: [ "main" ]
    paths:
      - "firebase/functions/**"
      - "firebase.json"
      - ".github/workflows/firebase-functions.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: firebase/functions
        run: npm ci

      - name: Build
        working-directory: firebase/functions
        run: npm run build

      # Auth to Google via Workload Identity (recommended)
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy functions
        run: firebase deploy --only functions --project akilipesa-prod
